version: '3'

services:
  app:
    container_name: laravel
    build: ./docker/laravel
    volumes:
      - ./var/www/app:/var/www/app
    working_dir: /var/www/app
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./var/www/app/public:/var/www/app/public
    ports:
      - 80:80
    links:
      - app
  mysql:
    build: ./docker/mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    links:
      - app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    ports:
      - 1234:80
    volumes:
      - /sessions